### ISSUE TITLE
Does not run compiled bytecode on Linux

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/hl#10]
I'm on Ubuntu 16.04 x64
```
$ haxe -hl hw.hl -main HelloWorld.hx
$ hl hw.hl
Invalid debug file

$ haxe -hl hw.hl -main HelloWorld.hx -debug
$ hl hw.hl
Invalid opcode
```

**Comment by ncannasse** [comment]
Are you using latest Haxe/GIT ? 3.3-RC will not be enough.

**Comment by RealyUniqueName** [comment]
I am

**Comment by ncannasse** [comment]
Did you compile hl with ARCH=32 ? atm HL/JIT only supports x86, not yet x86-64.

**Comment by RealyUniqueName** [comment]
I just executed `$ make`. I guess it's 32 by default because of this in makefile:
```
ifndef ARCH
ARCH=32
endif
```

**Comment by ncannasse** [comment]
It depends, some system/make already define ARCH, please run with  make ARCH=64 clean all

**Comment by RealyUniqueName** [comment]
Now it works
