### ISSUE TITLE
some constants are not defined when HL_64

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hl#5]
In [alloc.c](https://github.com/HaxeFoundation/hl/blob/master/src/alloc.c#L55-L61):
```c
#ifndef HL_64
#	define GC_MASK_BITS			16
#	define GC_LEVEL0_BITS		8
#	define GC_LEVEL1_BITS		8
#	define GC_GET_LEVEL1(ptr)	hl_gc_page_map[((unsigned int)(ptr))>>(GC_MASK_BITS+GC_LEVEL1_BITS)]
#	define GC_GET_PAGE(ptr)		GC_GET_LEVEL1(ptr)[(((unsigned int)(ptr))>>GC_MASK_BITS)&GC_LEVEL1_MASK]
#endif
```

`GC_LEVEL0_BITS` is used in the same file even if `HL_64`, so there is a compilation error.
This is blocking for CI since Travis only offer 64-bit environments.

**Comment by ncannasse** [comment]
(for the record)
I have not yet completed x64 support. Can you try with -m32 for now ?

**Comment by andyli** [comment]
Yes, `make hl32lib` works. Leaving this open until 64-bit support is done.
